# Generated by Django 2.2.16 on 2020-11-03 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=50)),
                ('city', models.CharField(default='NA', max_length=50)),
                ('country', models.CharField(default='NA', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StaffDataModel',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dept_name', models.CharField(max_length=50)),
                ('doctor_id', models.IntegerField()),
                ('hospital', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.HospitalDataModel')),
            ],
        ),
    ]
