# Generated by Django 2.2.16 on 2020-11-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdatamodel',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='staffdatamodel',
            name='username',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
