# Generated by Django 2.2.16 on 2020-11-03 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201103_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdatamodel',
            name='hospital',
            field=models.OneToOneField(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.HospitalDataModel'),
        ),
    ]
