# Generated by Django 2.2.16 on 2020-11-19 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201107_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffdatamodel',
            name='id',
        ),
        migrations.AddField(
            model_name='staffdatamodel',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='staffdatamodel',
            name='doctor_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staffdatamodel',
            name='username',
            field=models.CharField(max_length=15),
        ),
    ]
