# Generated by Django 2.2.16 on 2020-10-25 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPatinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(default='NA', max_length=50)),
                ('patient_id', models.CharField(max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('age', models.IntegerField(null=True)),
                ('image', models.ImageField(default='default.png', upload_to='retina_images')),
            ],
        ),
        migrations.CreateModel(
            name='DataDiabetic',
            fields=[
                ('patient_info', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='eyecare_app.DataPatinet')),
                ('result', models.IntegerField()),
                ('ai_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tested_on', models.DateField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
