# Generated by Django 2.2.16 on 2020-10-25 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eyecare_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='retina_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eyecare_app.DataPatinet')),
            ],
        ),
    ]
