# Generated by Django 2.2.16 on 2020-11-03 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newpatient', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientImage',
        ),
    ]
